bst< kt, vt, cmp > Class Template Reference
Templated implementation of a binary search tree class.
#include <bst.hpp>
Classes
class __iterator
Templated iterator class with a pointer to a node.
struct node
Templated node struct with two children nodes and one parent node.
Public Types
using pair_type = std::pair< const kt, vt >
using iterator = __iterator< node_type, pair_type >
using const_iterator = __iterator< node_type, const pair_type >
Public Member Functions
bst () noexcept=default
Default constructor for binary search tree.
bst (cmp op)
Custom constructor for binary search tree.
bst (const bst &B)
Copy constructor for binary search tree.
bst (bst &&B) noexcept
Move constructor for binary search tree.
bst & operator= (const bst &B)
Copy assignment for binary search tree.
bst & operator= (bst &&B) noexcept
Move assignment for binary search tree.
std::pair< iterator, bool > insert (const pair_type &x)
Inserts a new node in the binary search tree.
std::pair< iterator, bool > insert (pair_type &&x) noexcept
Inserts a new node in the binary search tree.
template<class... Types>
std::pair< iterator, bool > emplace (Types &&... args)
Inserts a new node in the binary search tree.
void clear () noexcept
Clears the tree freeing the memory of the taken by nodes.
iterator begin () noexcept
Used to begin an iteration on the binary search tree.
const_iterator begin () const noexcept
Used to begin an iteration on the binary search tree.
const_iterator cbegin () const noexcept
Used to begin an iteration on the binary search tree.
iterator end () noexcept
Used to finish an iteration on the binary search tree.
const_iterator end () const noexcept
Used to finish an iteration on the binary search tree.
const_iterator cend () const noexcept
Used to begin an iteration on the binary search tree.
iterator find (const kt &x) noexcept
Used to find a node inside the tree.
const_iterator find (const kt &x) const noexcept
Used to find a node inside the tree.
void balance () noexcept
Balances the tree.
vt & operator[] (const kt &x) noexcept
Operator [] overloading to access a node value in the tree or insert a new one.
vt & operator[] (kt &&x) noexcept
Operator [] overloading to access a node value in the tree or insert a new one.
void erase (const kt &x) noexcept
Removes a node from the tree if present.
template<class... Types>
std::pair< typename bst< kt, vt, cmp >::iterator, bool > emplace (Types &&... args)
Private Types
using node_type = node< std::pair< const kt, vt > >
Private Member Functions
bool op_eq (const kt &x, const kt &y) const noexcept
Checks if the keys are equal or not.
void order (std::vector< std::pair< kt, vt >> &v) noexcept
Auxiliary function needed by balance.
Private Attributes
cmp _op
Comparison operator for the binary search tree.
std::unique_ptr< node_type > head
Friends
std::ostream & operator<< (std::ostream &os, const bst &x)
Operator << overloading to print the tree according to the keys order.
Detailed Description
template<typename kt, typename vt, typename cmp = std::less<kt>>
class bst< kt, vt, cmp >
Templated implementation of a binary search tree class.
Template Parameters
kt Type of node keys.
vt Type of node values.
cmp Type of the custom comparison operator between nodes. Default std::less<kt>.
Definition at line 26 of file bst.hpp.
Member Typedef Documentation
const_iterator
template<typename kt, typename vt, typename cmp = std::less<kt>>
using bst< kt, vt, cmp >::const_iterator = __iterator<node_type, const pair_type>
Alias to make names shorter and intuitive.
Definition at line 88 of file bst.hpp.
iterator
template<typename kt, typename vt, typename cmp = std::less<kt>>
using bst< kt, vt, cmp >::iterator = __iterator<node_type, pair_type>
Alias to make names shorter and intuitive.
Definition at line 84 of file bst.hpp.
node_type
template<typename kt, typename vt, typename cmp = std::less<kt>>
using bst< kt, vt, cmp >::node_type = node<std::pair<const kt, vt> > [private]
Alias to make names shorter and intuitive.
Definition at line 48 of file bst.hpp.
pair_type
template<typename kt, typename vt, typename cmp = std::less<kt>>
using bst< kt, vt, cmp >::pair_type = std::pair<const kt, vt>
Alias to make names shorter and intuitive.
Definition at line 80 of file bst.hpp.
Constructor & Destructor Documentation
bst() [1/3]
template<typename kt, typename vt, typename cmp = std::less<kt>>
bst< kt, vt, cmp >::bst (cmp op) [inline]
Custom constructor for binary search tree.
Parameters
op Comparison operator between nodes.
Definition at line 101 of file bst.hpp.
bst() [2/3]
template<typename kt, typename vt, typename cmp = std::less<kt>>
bst< kt, vt, cmp >::bst (const bst< kt, vt, cmp > & B) [inline]
Copy constructor for binary search tree.
Parameters
B The binary search tree to be copied into a new one.
The method performs a deep copy of the tree calling a custom constructor of the node.
Definition at line 113 of file bst.hpp.
References bst< kt, vt, cmp >::head.
bst() [3/3]
template<typename kt, typename vt, typename cmp = std::less<kt>>
bst< kt, vt, cmp >::bst (bst< kt, vt, cmp > && B) [inline], [noexcept]
Move constructor for binary search tree.
Parameters
B The binary search tree to be moved into a new one.
Definition at line 126 of file bst.hpp.
Member Function Documentation
balance()
template<typename kt , typename vt , typename cmp >
void bst< kt, vt, cmp >::balance () [noexcept]
Balances the tree.
Creates a sorted vector of pairs key and value, clears the tree and passes the vector to the previously defined private function order.
Definition at line 238 of file bst_functions.hpp.
Referenced by bst< kt, vt, cmp >::cend().
begin() [1/2]
template<typename kt, typename vt, typename cmp = std::less<kt>>
iterator bst< kt, vt, cmp >::begin () [inline], [noexcept]
Used to begin an iteration on the binary search tree.
Returns
iterator An iterator to the leftmost node of the tree.
Definition at line 218 of file bst.hpp.
References bst< kt, vt, cmp >::node< pair_type >::_left.
begin() [2/2]
template<typename kt, typename vt, typename cmp = std::less<kt>>
const_iterator bst< kt, vt, cmp >::begin () const [inline], [noexcept]
Used to begin an iteration on the binary search tree.
Returns
const_iterator A constant iterator to the leftmost node of the tree.
Definition at line 233 of file bst.hpp.
References bst< kt, vt, cmp >::node< pair_type >::_left.
cbegin()
template<typename kt, typename vt, typename cmp = std::less<kt>>
const_iterator bst< kt, vt, cmp >::cbegin () const [inline], [noexcept]
Used to begin an iteration on the binary search tree.
Returns
const_iterator A constant iterator to the leftmost node of the tree.
Implemented to assure the user of returning a constant iterator.
Definition at line 250 of file bst.hpp.
References bst< kt, vt, cmp >::node< pair_type >::_left.
cend()
template<typename kt, typename vt, typename cmp = std::less<kt>>
const_iterator bst< kt, vt, cmp >::cend () const [inline], [noexcept]
Used to begin an iteration on the binary search tree.
Returns
const_iterator A constant iterator to one past the rightmost node of the tree.
Implemented to assure the user of returning a constant iterator.
Definition at line 299 of file bst.hpp.
References bst< kt, vt, cmp >::node< pair_type >::_right, bst< kt, vt, cmp >::balance(), and bst< kt, vt, cmp >::find().
emplace()
template<typename kt, typename vt, typename cmp = std::less<kt>>
template<class... Types>
std::pair<iterator,bool> bst< kt, vt, cmp >::emplace (Types &&... args)
Inserts a new node in the binary search tree.
Template Parameters
Types Types of the variable number of parameters.
Parameters
args Variable number of parameters.
Returns
std::pair<iterator, bool> A pair of an iterator and a bool.
A node is created. If the key is already present in the tree, the node is destroyed, else it's inserted.
Referenced by bst< kt, vt, cmp >::insert(), and bst< kt, vt, cmp >::operator=().
end() [1/2]
template<typename kt, typename vt, typename cmp = std::less<kt>>
iterator bst< kt, vt, cmp >::end () [inline], [noexcept]
Used to finish an iteration on the binary search tree.
Returns
iterator A iterator to one past the rightmost node of the tree.
Definition at line 265 of file bst.hpp.
References bst< kt, vt, cmp >::node< pair_type >::_right.
end() [2/2]
template<typename kt, typename vt, typename cmp = std::less<kt>>
const_iterator bst< kt, vt, cmp >::end () const [inline], [noexcept]
Used to finish an iteration on the binary search tree.
Returns
iterator A constant iterator to one past the rightmost node of the tree.
Definition at line 281 of file bst.hpp.
References bst< kt, vt, cmp >::node< pair_type >::_right.
erase()
template<typename kt, typename vt , typename cmp >
void bst< kt, vt, cmp >::erase (const kt & x) [noexcept]
Removes a node from the tree if present.
Parameters
x The key of the node to be removed.
After removing a node the ordering of the tree is preserved.
Definition at line 262 of file bst_functions.hpp.
References bst< kt, vt, cmp >::__iterator< node_type, pair_type >::_current, bst< kt, vt, cmp >::node< pair_type >::_left, bst< kt, vt, cmp >::node< pair_type >::_parent, and bst< kt, vt, cmp >::node< pair_type >::_right.
find() [1/2]
template<typename kt, typename vt , typename cmp >
bst< kt, vt, cmp >::iterator bst< kt, vt, cmp >::find (const kt & x) [noexcept]
Used to find a node inside the tree.
Parameters
x The key of the node to be found.
Returns
iterator An iterator to the node if found, else to end().
Definition at line 172 of file bst_functions.hpp.
References bst< kt, vt, cmp >::node< pair_type >::_element, bst< kt, vt, cmp >::node< pair_type >::_left, and bst< kt, vt, cmp >::node< pair_type >::_right.
Referenced by bst< kt, vt, cmp >::cend().
find() [2/2]
template<typename kt, typename vt , typename cmp >
bst< kt, vt, cmp >::const_iterator bst< kt, vt, cmp >::find (const kt & x) const [noexcept]
Used to find a node inside the tree.
Parameters
x The key of the node to be found.
Returns
const_iterator A constant iterator to the node if found, else to end().
Definition at line 201 of file bst_functions.hpp.
References bst< kt, vt, cmp >::node< pair_type >::_element, bst< kt, vt, cmp >::node< pair_type >::_left, and bst< kt, vt, cmp >::node< pair_type >::_right.
insert() [1/2]
template<typename kt , typename vt , typename cmp >
std::pair< typename bst< kt, vt, cmp >::iterator, bool > bst< kt, vt, cmp >::insert (const pair_type & x)
Inserts a new node in the binary search tree.
Parameters
x The pair key and value to be inserted.
Returns
std::pair<iterator, bool> A pair of an iterator and a bool.
The iterator of the pair points to the inserted node or the previously existent node with the same key if one is present. If the insertion were successful the bool is true, else false. The pair is copied into the node.
Definition at line 52 of file bst_functions.hpp.
Referenced by bst< kt, vt, cmp >::operator=(), and bst< kt, vt, cmp >::operator[]().
insert() [2/2]
template<typename kt , typename vt , typename cmp >
std::pair< typename bst< kt, vt, cmp >::iterator, bool > bst< kt, vt, cmp >::insert (pair_type && x) [noexcept]
Inserts a new node in the binary search tree.
Parameters
x The pair key and value to be inserted.
Returns
std::pair<iterator, bool> A pair of an iterator and a bool.
The iterator of the pair points to the inserted node or the previously existent node with the same key if one is present. If the insertion were successful the bool is true, else false. The pair is moved into the node.
Definition at line 87 of file bst_functions.hpp.
References bst< kt, vt, cmp >::node< pair_type >::_parent, and bst< kt, vt, cmp >::emplace().
op_eq()
template<typename kt, typename vt, typename cmp = std::less<kt>>
bool bst< kt, vt, cmp >::op_eq (const kt & x, const kt & y) const [inline], [private], [noexcept]
Checks if the keys are equal or not.
Parameters
x The first key to be compared.
y The second key to be compared.
Returns
True if the two keys are equal, else false.
Definition at line 61 of file bst.hpp.
References bst< kt, vt, cmp >::_op, and bst< kt, vt, cmp >::order().
operator=() [1/2]
template<typename kt, typename vt, typename cmp = std::less<kt>>
bst& bst< kt, vt, cmp >::operator= (const bst< kt, vt, cmp > & B) [inline]
Copy assignment for binary search tree.
Parameters
B The binary search tree to be copied into an existing one.
Returns
bst& The modified existing tree.
Definition at line 139 of file bst.hpp.
References bst< kt, vt, cmp >::clear(), and bst< kt, vt, cmp >::head.
operator=() [2/2]
template<typename kt, typename vt, typename cmp = std::less<kt>>
bst& bst< kt, vt, cmp >::operator= (bst< kt, vt, cmp > && B) [inline], [noexcept]
Move assignment for binary search tree.
Parameters
B The binary search tree to be moved into an existing one.
Returns
bst& The modified existing tree.
Definition at line 157 of file bst.hpp.
References bst< kt, vt, cmp >::emplace(), and bst< kt, vt, cmp >::insert().
operator[]() [1/2]
template<typename kt, typename vt, typename cmp = std::less<kt>>
vt& bst< kt, vt, cmp >::operator[] (const kt & x) [inline], [noexcept]
Operator [] overloading to access a node value in the tree or insert a new one.
Parameters
x The key of the node whose value should be accessed.
Returns
vt& A reference to the value of the accessed node.
It calls the copy implementation of the insert function.
Definition at line 344 of file bst.hpp.
References bst< kt, vt, cmp >::insert().
operator[]() [2/2]
template<typename kt, typename vt, typename cmp = std::less<kt>>
vt& bst< kt, vt, cmp >::operator[] (kt && x) [inline], [noexcept]
Operator [] overloading to access a node value in the tree or insert a new one.
Parameters
x The key of the node whose value should be accessed.
Returns
vt& A reference to the value of the accessed node.
It calls the move implementation of the insert function.
Definition at line 360 of file bst.hpp.
References bst< kt, vt, cmp >::insert().
order()
template<typename kt, typename vt, typename cmp >
void bst< kt, vt, cmp >::order (std::vector< std::pair< kt, vt >> & v) [private], [noexcept]
Auxiliary function needed by balance.
Parameters
v A vector of pairs in ascending order.
Iterative function inserting in the tree the central element and subdivides the vector in two halves, then it calls itself on these two halves.
Definition at line 22 of file bst_functions.hpp.
Referenced by bst< kt, vt, cmp >::op_eq().
Friends And Related Function Documentation
operator<<
template<typename kt, typename vt, typename cmp = std::less<kt>>
std::ostream& operator<< (std::ostream & os, const bst< kt, vt, cmp > & x) [friend]
Operator << overloading to print the tree according to the keys order.
Parameters
os The output stream to which the strings to be printed are appended.
x The tree to be printed.
Returns
std::ostream& The output stream to which strings have been appended.
It calls cbegin() and cend() to be sure the tree is unchanged by the iterators.
Definition at line 377 of file bst.hpp.
Member Data Documentation
head
template<typename kt, typename vt, typename cmp = std::less<kt>>
std::unique_ptr<node_type> bst< kt, vt, cmp >::head [private]
Root node of the binary search tree.
Definition at line 52 of file bst.hpp.
Referenced by bst< kt, vt, cmp >::bst(), and bst< kt, vt, cmp >::operator=().
The documentation for this class was generated from the following files:
include/bst.hpp
include/bst_functions.hpp